<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\LoomLCI.Core\LoomLCI.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="PdfPig" Version="0.1.16" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
